---
  - hosts: all
    become: true
    tasks:
      - name: Installing httpd
        yum: name=httpd state=present
          
      - name: Setting the http server page for apache
        shell: echo "<h1> Hell Yeah!</h1>" > /var/www/html/index.html
        
      - name: Starting the Apache service
        service: name=httpd state=started enabled=yes